import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = async (path) => readFile(new URL(path, root), "utf8");

test("all V7 website images have clear upload placements", async () => {
  const media = await source("src/server/media.ts");
  const schema = await source("db/media.sql");
  const admin = await source("src/pages/admin666.astro");
  const placements = await source("src/data/siteMedia.ts");
  const loader = await source("src/components/SiteMediaLoader.astro");
  const home = await source("src/components/HomeV7Landing.astro");
  const pilot = await source("src/pages/pilot-families.astro");
  const about = await source("src/pages/about-harbor.astro");
  assert.match(media, /image\/jpeg/);
  assert.match(media, /image\/png/);
  assert.match(media, /image\/gif/);
  assert.match(media, /siteMediaPlacementKeys/);
  assert.match(media, /payload\.action === "assign"/);
  assert.match(media, /update site_media set active = false where slot = \$\{slot\}/);
  assert.match(media, /create table if not exists site_media/);
  assert.doesNotMatch(media, /BLOB_READ_WRITE_TOKEN is not configured/);
  assert.doesNotMatch(media, /token:\s*blobToken/);
  assert.match(media, /await del\(String\(rows\[0\]\.url\)\)/);
  assert.match(schema, /site_media_slot_v2_check/);
  assert.match(schema, /home-carousel-pilot/);
  assert.match(schema, /about-harbor-os/);
  assert.match(admin, /accept="image\/jpeg,image\/png,image\/gif"/);
  assert.match(admin, /data-tab-button="media"/);
  assert.match(admin, /Website image locations/);
  assert.match(admin, /Upload and use/);
  assert.match(admin, /Restore default/);
  assert.doesNotMatch(admin, /<option value="page">Other page media<\/option>/);
  assert.equal((placements.match(/key: "/g) || []).length, 16);
  assert.match(placements, /pagePath: "\/home-v7 - Top carousel, slide 1"/);
  assert.match(placements, /pagePath: "\/pilot-families - Hero"/);
  assert.match(placements, /pagePath: "\/about-harbor - Project 02"/);
  assert.match(loader, /querySelectorAll\("\[data-media-slot\]"\)/);
  assert.match(loader, /home-carousel-memory/);
  assert.match(home, /data-media-slot="home-hardware"/);
  assert.match(pilot, /data-media-slot="pilot-hero"/);
  assert.match(about, /data-media-slot="about-harbor-os"/);
});
