create extension if not exists pgcrypto;

create table if not exists pilot_family_surveys (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  adult_confirmed boolean not null,
  stable_wifi_confirmed boolean not null,
  compatible_device_confirmed boolean not null,
  pilot_commitment_confirmed boolean not null,
  selection_acknowledged boolean not null,
  on_camera_willingness text not null,
  filming_ability text not null,
  audience_level text not null,
  story_sample text not null,
  core_scenarios jsonb not null default '[]'::jsonb,
  household_context jsonb not null default '[]'::jsonb,
  device_categories jsonb not null default '[]'::jsonb,
  available_windows jsonb not null default '[]'::jsonb,
  scheduling_confidence text not null,
  completion_commitment text not null,
  past_participation_level text not null,
  referral_source text not null,
  accuracy_confirmed boolean not null,
  review_contact_confirmed boolean not null,
  disclosure_confirmed boolean not null,
  no_marketing_acknowledged boolean not null,
  content_score integer not null,
  scenario_score integer not null,
  reliability_score integer not null,
  total_score integer not null,
  score_band text not null,
  score_version text not null,
  automatic_summary text not null,
  route text,
  path text,
  referrer text,
  session_id text,
  visitor_id text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pilot_family_surveys_total_score_check check (total_score between 0 and 100),
  constraint pilot_family_surveys_score_band_check check (score_band in ('priority', 'qualified', 'conditional', 'not_priority'))
);

create index if not exists pilot_family_surveys_score_idx on pilot_family_surveys (total_score desc, created_at desc);
create index if not exists pilot_family_surveys_band_idx on pilot_family_surveys (score_band, created_at desc);
